debugging

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,12 +1,12 @@
   spinner() {
-	local pid=\$!
+	local pid=$!
 	local delay=0.75
 	local spinstr='|/-\'
-	while [ "\$(ps a | awk '{print \$1}' | grep \$pid)" ]; do
-	  local temp=\${spinstr#?}
-	  printf " [%c]  " "\$spinstr" 2>&1 | tee -a /dev/tty0
-	  local spinstr=\$temp\${spinstr%"\$temp"}
-	  sleep \$delay
+	while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
+	  local temp=${spinstr#?}
+	  printf " [%c]  " "$spinstr" 2>&1 | tee -a /dev/tty0
+	  local spinstr=$temp${spinstr%"$temp"}
+	  sleep $delay
 	  printf "\b\b\b\b\b\b" 2>&1 | tee -a /dev/tty0
 	done
 	printf "    \b\b\b\b" 2>&1 | tee -a /dev/tty0
@@ -14,30 +14,30 @@
   
   run()
   {
-	local msg=\$1
-	local runThis=\$2
-	local log=\$3
-	echo -e "\e[1m\e[4m\$(date | awk '{print \$4}') - \$msg...\e[0m" 2>&1 | tee -a /dev/tty0
-	echo "\$(date) START: Running \$runThis..." >> \$log
-	if [ "\$debug" = true ]; then
-	  unbuffer \$runThis \$verbose | tee -a \$log /dev/tty0
+	local msg=$1
+	local runThis=$2
+	local log=$3
+	echo -e "\e[1m\e[4m$(date | awk '{print $4}') - $msg...\e[0m" 2>&1 | tee -a /dev/tty0
+	echo "$(date) START: Running $runThis..." >> $log
+	if [ "$debug" = true ]; then
+	  unbuffer $runThis $verbose | tee -a $log /dev/tty0
 	else
-	  (eval \$runThis >> \$log 2>&1) &
+	  (eval $runThis >> $log 2>&1) &
 	  spinner
 	  wait %1
-	  exitcode=\$?
-	  if [ \$exitcode -ne 0 ]; then
+	  exitcode=$?
+	  if [ $exitcode -ne 0 ]; then
 		local success=false
 	  else
 		local success=true
 	  fi
-	  if [ "\$success" = false ]; then
-		echo "\$(date) FAILED: Running \$runThis..." >> \$log
-		echo -e "\e[1m[\e[31mFAILED: Running \$runThis\e[39m]" 2>&1 | tee -a /dev/tty0
-		echo -e "\e[1mPlease check the file \$log." 2>&1 | tee -a /dev/tty0
+	  if [ "$success" = false ]; then
+		echo "$(date) FAILED: Running $runThis..." >> $log
+		echo -e "\e[1m[\e[31mFAILED: Running $runThis\e[39m]" 2>&1 | tee -a /dev/tty0
+		echo -e "\e[1mPlease check the file $log." 2>&1 | tee -a /dev/tty0
 		exit 1
 	  else
-		echo "\$(date) SUCCESS: Running \$runThis..." >> \$log
+		echo "$(date) SUCCESS: Running $runThis..." >> $log
 		echo -e "\e[1m[\e[32msuccess\e[39m]" 2>&1 | tee -a /dev/tty0
 	  fi
 	fi
